import {
  CarEight,
  CarFive,
  CarFour,
  CarOne,
  CarSeven,
  CarSix,
  CarThree,
  CarTwo,
} from "../../../assets/img";

export const direction = [
  {
    id: 1,
    title: "Mercedes-Maybach",
    description:
      "Состояние машины, Марка машины / Кол-во пассажирских мест / Цвет",
    time: "9:00 - 20:00",
    color: "Черный",
    cost: 500,
    currency: 10,
    country: "Ташкенту",
    images: CarOne,
  },
  {
    id: 2,
    title: "Mercedes-Benz",
    description:
      "Состояние машины, Марка машины / Кол-во пассажирских мест / Цвет",
    time: "9:00 - 20:00",
    color: "Черный",
    cost: 500,
    currency: 10,
    country: "Ташкенту",
    images: CarTwo,
  },
  {
    id: 3,
    title: "Mercedes-Benz",
    description:
      "Состояние машины, Марка машины / Кол-во пассажирских мест / Цвет",
    time: "9:00 - 20:00",
    color: "Черный",
    cost: 500,
    currency: 10,
    country: "Ташкенту",
    images: CarThree,
  },
  {
    id: 4,
    title: "Chevrolet Malibu ",
    description:
      "Состояние машины,Марка машины / Кол-во пассажирских мест / Цвет",
    time: "9:00 - 20:00",
    color: "Черный",
    cost: 500,
    currency: 10,
    country: "Ташкенту",
    images: CarFour,
  },
  {
    id: 5,
    title: "Mersedez-Benz Viano",
    description:
      "Состояние машины,Марка машины / Кол-во пассажирских мест / Цвет",
    time: "9:00 - 20:00",
    color: "Черный",
    cost: 500,
    currency: 10,
    country: "Ташкенту",
    images: CarFive,
  },
  {
    id: 6,
    title: "Mercedes Sprinter ",
    description:
      "Состояние машины,Марка машины / Кол-во пассажирских мест / Цвет",
    time: "9:00 - 20:00",
    color: "Черный",
    cost: 500,
    currency: 10,
    country: "Ташкенту",
    images: CarSix,
  },
  {
    id: 7,
    title: "Hyundai h1",
    description:
      "Состояние машины,Марка машины / Кол-во пассажирских мест / Цвет",
    time: "9:00 - 20:00",
    color: "Черный",
    cost: 500,
    currency: 10,
    country: "Ташкенту",
    images: CarSeven,
  },
  {
    id: 8,
    title: "Higer",
    description: "Состояние машины,Марка машины - Кол-во пассажирских мест",
    time: "9:00 - 20:00",
    color: "Черный",
    cost: 500,
    currency: 10,
    country: "Ташкенту",
    images: CarEight,
  },
];
